---
id: Reflection
name: Reflection
full: Method reflection and documentation library
description: |
  The Reflection package provides methods for generationg code reflection and automatic documentation of methods.
  The package has a driver based output generation and currently generates HTML and Text_Wiki output.
list: dev
